/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.builder.SpringApplicationBuilder

@SpringBootApplication
class App

fun main(args:  Array<String>) {
    val application = SpringApplicationBuilder()
        .sources(App::class.java)
        .build()
    application.run(*args)
}
