/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import jakarta.annotation.PostConstruct
import org.springframework.batch.core.Job
import org.springframework.batch.core.JobParametersBuilder
import org.springframework.batch.core.Step
import org.springframework.batch.core.StepContribution
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing
import org.springframework.batch.core.job.builder.JobBuilder
import org.springframework.batch.core.launch.JobLauncher
import org.springframework.batch.core.repository.JobRepository
import org.springframework.batch.core.scope.context.ChunkContext
import org.springframework.batch.core.step.builder.StepBuilder
import org.springframework.batch.repeat.RepeatStatus
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.builder.SpringApplicationBuilder
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder
import org.springframework.jdbc.support.JdbcTransactionManager
import org.springframework.stereotype.Component
import org.springframework.transaction.PlatformTransactionManager
import java.time.LocalDate
import javax.sql.DataSource


@Configuration
open class DataSourceConfiguration {

    @Bean
    open fun dataSource(): DataSource {
        return EmbeddedDatabaseBuilder()
            .addScript("/org/springframework/batch/core/schema-hsqldb.sql")
            .build()
    }

    @Bean
    open fun transactionManager(dataSource: DataSource): JdbcTransactionManager {
        return JdbcTransactionManager(dataSource)
    }
}

@Configuration
@EnableBatchProcessing
open class HelloWorldJobConfiguration {

    @Bean
    open fun step(
        jobRepository: JobRepository,
        transactionManager: PlatformTransactionManager
    ): Step {
        return StepBuilder(
            "step",
            jobRepository
        ).tasklet({ _: StepContribution, _: ChunkContext ->
            println("Hello world!")
            RepeatStatus.FINISHED
        }, transactionManager).build()
    }

    @Bean
    open fun job(jobRepository: JobRepository, step: Step): Job {
        return JobBuilder("job", jobRepository).start(step).build()
    }
}

@Component
open class HelloWorldJobLauncher(
    private val jobLauncher: JobLauncher,
    private val job: Job
) {

    @PostConstruct
    fun run() {
        val jobParameters = JobParametersBuilder()
            .addLocalDate("date", LocalDate.now())
            .toJobParameters()

        jobLauncher.run(job, jobParameters)
    }
}

@SpringBootApplication
open class App

fun main(args:  Array<String>) {
    val application = SpringApplicationBuilder()
        .sources(App::class.java)
        .build()
    application.run(*args)
}
